Feature-menu
AlexKabaiev/project-13 pull request #14
Opened 2022-12-03 17:51 UTC by IanaKozma

Please, check.

2022-12-03 20:38 UTC, AlexKabaiev requested changes
Приветствую. Есть несколько замечаний по вашей работе. Хочу уточнить почему Вы использовали разные имена файлов menu.html и _menu-section.scss, думаю что логичнее когда они имеют одно имя. У вас в ветке есть лишние файлы index.css index.css.map это значит что вы используете watch sass, что делать не нужно. Так же в menu.html должен код начинаться с <section> head main body не нужно прописывать.

2022-12-03 20:38 UTC, AlexKabaiev commented on src/partials/restaurant/menu.html
> +    <main>
Этого быть не должно

2022-12-03 20:38 UTC, AlexKabaiev commented on src/partials/restaurant/menu.html
> +                <h2 class="menu-section__title">МЕНЮ РЕСТОРАНУ</h2>
Лучше не использовать в коде заглавные буквы а в стилях для этого заголовка указать text-transform: uppercase;

2022-12-03 20:38 UTC, AlexKabaiev commented on src/sass/components/_menu-section.scss
> +.menu-section__title {
тут нужно добавить text-transform: uppercase;

2022-12-04 09:47 UTC, IanaKozma commented on src/partials/restaurant/menu.html
> +    <main>
fixed

2022-12-04 09:47 UTC, IanaKozma commented on src/partials/restaurant/menu.html
> +                <h2 class="menu-section__title">МЕНЮ РЕСТОРАНУ</h2>
fixed

2022-12-04 09:47 UTC, IanaKozma commented on src/sass/components/_menu-section.scss
> +.menu-section__title {
fixed

2022-12-04 10:47 UTC, AlexKabaiev reviewed
Почти всё ок, но есть конфликт с основной веткой, пожалуйста обнови у себя main и отправь свою ветку снова, чтобы у тебя были все актуальные изменения, тогда думаю конфликт уйдёт и я сделаю слияние

2022-12-04 11:03 UTC, IanaKozma commented
> Почти всё ок, но есть конфликт с основной веткой, пожалуйста обнови у себя main и отправь свою ветку снова, чтобы у тебя были все актуальные изменения, тогда думаю конфликт уйдёт и я сделаю слияние

Я вроде все пофиксила. Попробуй слить ветку.

2022-12-04 12:36 UTC, AlexKabaiev approved these changes

2022-12-04 13:05 UTC, closed without merging