Feature modal table
AlexKabaiev/project-13 pull request #5
Opened 2022-12-01 20:18 UTC by Andrii-Verhun

Модалка на столик с переходами на кнопке, кастомным селектом и кастомной маской для ввода номера телефона.

2022-12-01 20:19 UTC, Andrii-Verhun commented
Сделал как и говорили, выкачал актуальную версию проекта и заново внес свои изменения. Так что поламать ничего не должен))

2022-12-02 08:57 UTC, Andrii-Verhun commented
По поводу того что я добавил ИКОНКУ стрелки вниз отдельно, это потому что иначе впихнуть ее в псевдоэлемент (как того требует ТЗ) невозможно

2022-12-02 13:11 UTC, Andrii-Verhun commented
Модалки готовы

2022-12-02 18:02 UTC, filipchukdv approved these changes

2022-12-03 11:05 UTC, anastizs approved these changes

2022-12-03 21:04 UTC, AlexKabaiev requested changes
В hotel.html не правильная разметка нужно убрать header, main, footer Если ты обновиш у себя основную ветку, чтобы подтянулись изменения в проекте и потом свою закинешь снова, то я сделаю слияние, код крутой!

2022-12-04 08:57 UTC, AlexKabaiev approved these changes

2022-12-04 09:04 UTC, AlexKabaiev reviewed
У тебя index.scss не обновлён, обнови пожалуйста у себя основную ветку и свою и закинь обратно, я сделаю слияние. Может после этого уйдёт конфликт

2022-12-04 10:31 UTC, AlexKabaiev approved these changes

2022-12-04 10:32 UTC, merged